---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # This must be a combination of the spec.names.plural + spec.group
  name: memcacheds.cache.example.com
spec:
  # This is the api "namespace" you define for yourself.
  # Usually some subdomain of your organisation site url.
  group: cache.example.com
  # This defines the names under which you can list created resources of this kind,
  # using kubectl for example
  names:
    kind: Memcached
    plural: memcacheds
  # Either Namespaced or Cluster-scoped.
  scope: Namespaced
  # `versions` is mandatory:
  # there should be at least one version that is served and stored.
  versions:
    # You usually start out with some kind of alpha version.
    # Be sure to create a roadmap on how to get to a stable "v1".
    - name: v1alpha1
      served: true
      # See also: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # Like the `spec` key this key resides under, any custom resource
            # created as kind `Memcached` will need a `spec` key.
            spec:
              type: object
              properties:
                # So the only spec key will be a `size` parameter as integer
                # All tutorial business, of course
                size:
                  type: integer
                  description: The number of replicas for the Memcached deployment
