apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: memcached-source
spec:
  template:
    # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
    serviceAccountName: memcached-sa
  resource:
    memcached:
      group: cache.example.com
      version: v1alpha1
      resource: memcacheds
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
      filter:
        afterStart: true
