apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: memcached-source
spec:
  template:
    # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
    serviceAccountName: memcached-sa
  resource:
    memcached:
      group: cache.example.com
      version: v1alpha1
      resource: memcacheds
      eventTypes:
        # Types: https://github.com/argoproj/argo-events/blob/00e2ae801addcd362a22613a745ae424932efa40/pkg/apis/eventsource/v1alpha1/types.go#L280
        - ADD
        - UPDATE
        - DELETE
      filter:
        afterStart: true
