---
# This is just a tutorial setup - adapt
# to your access control requirements
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memcached-role
kind: ClusterRole
rules:
  - verbs:
      - get
      - list
      - create
      - watch
      - patch
      - update
      - post
      - put
      - delete
    resources:
      - memcacheds
      - workflows
      - workflowtemplates
      - deployments
      - pods
    apiGroups:
      - cache.example.com
      - argoproj.io
      - apps
      # Core API group: for pods
      - ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memcached-rb
roleRef:
  name: memcached-role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: memcached-sa
    # In case you installed Argo Events in a different namespace:
    # adapt namespace here
    namespace: argo-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memcached-sa
  namespace: argo-events
