---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memcached-role
kind: ClusterRole
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - update
      - post
      - put
      - delete
    resources:
      - memcacheds
    apiGroups:
      - cache.example.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memcached-rb
roleRef:
  name: memcached-role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: memcached-sa
    namespace: argo-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memcached-sa
  namespace: argo-events
