---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: memcached-sensor
spec:
  template:
    serviceAccountName: memcached-sa
  dependencies:
    - name: source-dependency
      # References the metadata.name in the event source
      eventSourceName: memcached-source
      # References the key directly under "resource:" in the event source
      eventName: memcached
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: deploy-memcached-workflow-
              spec:
                serviceAccountName: memcached-sa
                entrypoint: deploy-memcached-template
                arguments:
                  parameters:
                    - name: replicas
                      # This value gets overridden, see the template.k8s.parameter below
                      value: 1
                templates:
                  - name: deploy-memcached-template
                    steps:
                      - - name: call-template
                          templateRef:
                            name: memcached-deploy-workflow-template
                            template: main

          # This is the definition of what data gets injected from the source into the resource generated by the sensor
          parameters:
            - src:
                dependencyName: source-dependency
                # This is the `size` parameter, see the custom resource definition
                dataKey: body.spec.size
              dest: spec.arguments.parameters.0.value
