---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: memcached-sensor
spec:
  template:
    serviceAccountName: memcached-sa
  dependencies:
    - name: source-dependency
      # References the metadata.name in the event source
      eventSourceName: memcached-source
      # References the key directly under "resource:" in the event source
      eventName: memcached
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: memcached
              spec:
                serviceAccountName: argo-events-sa
                # This value gets overridden, see the template.k8s.parameter below
                replicas: 1
                selector:
                  matchLabels:
                    app: memcached
                template:
                  metadata:
                    labels:
                      app: memcached
                  spec:
                    containers:
                      - name: memcached
                        command:
                          - memcached
                          - -m=64
                          - -o
                          - modern
                          - -v
                        image: "docker.io/memcached:1.4.36-alpine"
                        ports:
                          - containerPort: 11211

          # This is the definition of what data gets injected from the source into the resource generated by the sensor
          parameters:
            - src:
                dependencyName: source-dependency
                # This is the `size` parameter, see the custom resource definition
                dataKey: body.size
              dest: spec.replicas
