apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: memcached-deploy-workflow-template
spec:
  arguments:
    parameters:
      - name: message
        value: ""  # Overridden by Sensor workflow
      - name: replicas
        value: "1" # Overridden by Sensor workflow
  templates:
    - name: main
      steps:
        - - name: log-message
            template: log
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.message}}"

        - - name: parameterize-replicas
            template: operator-logic
            arguments:
              parameters:
                - name: manifest
                  value: |
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: memcached-deployment
                      labels:
                        app: memcached
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          app: memcached
                      template:
                        metadata:
                          labels:
                            app: memcached
                        spec:
                          containers:
                            - name: memcached
                              command:
                                - memcached
                                - -m=64
                                - -o
                                - modern
                                - -v
                              image: "docker.io/memcached:1.4.36-alpine"
                              ports:
                                - containerPort: 11211

        - - name: print-result
            template: print
            arguments:
              parameters:
                - name: manifest
                  value: "{{steps.parameterize-replicas.outputs.result}}"

    - name: log
      inputs:
        parameters:
          - name: message
      container:
        name: simple-logger
        image: ubuntu:latest
        command:
          - echo
        args:
          - "{{inputs.parameters.message}}"

    - name: operator-logic
      inputs:
        parameters:
          - name: manifest
      script:
        name: set-replicas
        image: quay.io/ansible/ansible-runner
        command:
          - python3
        source: |
          import yaml

          manifest = yaml.load("""
          {{inputs.parameters.manifest}}
          """)
          manifest['spec']['replicas'] = int({{workflow.parameters.replicas}})
          result = yaml.dump(manifest)
          print(result)
    - name: print
      inputs:
        parameters:
          - name: manifest
      container:
        name: print-manifest
        image: ubuntu:latest
        command:
          - echo
          - "{{inputs.parameters.manifest}}"

  entrypoint: main
  serviceAccountName: memcached-sa
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
