---
# {% raw %} The workflow template that does the "heavy lifting"
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: memcached-deploy-workflow-template
spec:
  arguments:
    parameters:
      - name: message
        value: ""  # Overridden by Sensor workflow
      - name: replicas
        value: "1" # Overridden by Sensor workflow
  templates:
    - name: main
      steps:
        - - name: log-message
            template: log
            arguments:
              parameters:
                - name: content
                  value: "{{workflow.parameters.message}}"

        - - name: log-operation
            template: log
            arguments:
              parameters:
                - name: content
                  value: "{{workflow.parameters.operation}}"

        - - name: parameterize-replicas
            template: operator-logic
            arguments:
              parameters:
                - name: manifest
                  value: |
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: memcached-deployment
                      labels:
                        app: memcached
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          app: memcached
                      template:
                        metadata:
                          labels:
                            app: memcached
                        spec:
                          containers:
                            - name: memcached
                              command:
                                - memcached
                                - -m=64
                                - -o
                                - modern
                                - -v
                              image: "docker.io/memcached:1.4.36-alpine"
                              ports:
                                - containerPort: 11211

        - - name: log-result
            template: log
            arguments:
              parameters:
                - name: content
                  value: "{{steps.parameterize-replicas.outputs.result}}"

        - - name: map-operation-to-action
            template: operation-mapping

        - - name: log-action
            template: log
            arguments:
              parameters:
                - name: content
                  value: "{{steps.map-operation-to-action.outputs.result}}"

        - - name: deploy-memcached
            template: deploy
            arguments:
              parameters:
                - name: action
                  value: "{{steps.map-operation-to-action.outputs.result}}"
                - name: manifest
                  value: "{{steps.parameterize-replicas.outputs.result}}"

    - name: log
      inputs:
        parameters:
          - name: content
      container:
        name: simple-logger
        image: ubuntu:latest
        command:
          - echo
        args:
          - "{{inputs.parameters.content}}"

    - name: operator-logic
      inputs:
        parameters:
          - name: manifest
      script:
        image: quay.io/ansible/ansible-runner
        command:
          - python3
        source: |
          import yaml

          manifest = yaml.load("""
          {{inputs.parameters.manifest}}
          """)
          manifest['spec']['replicas'] = int({{workflow.parameters.replicas}})
          result = yaml.dump(manifest)
          print(result)

    - name: operation-mapping
      script:
        image: quay.io/ansible/ansible-runner
        command:
          - python3
        source: |
          mapping = {
            "ADD": "apply",
            "UPDATE": "apply",
            "DELETE": "delete",
          }
          print(mapping["{{workflow.parameters.operation}}"])

    - name: deploy
      inputs:
        parameters:
          - name: action
          - name: manifest
      resource:
        action: "{{inputs.parameters.action}}"
        manifest: "{{inputs.parameters.manifest}}"

  entrypoint: main
  serviceAccountName: memcached-sa
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
# {% endraw %}
