# Site settings
title: "Rein van 't Veer"
email: reinvantveer at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  The personal pages for Rein van 't Veer, 
  geospatial and semantic web developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bureaudigitaalerfgoed.nl" # the base hostname & protocol for your site
twitter_username: reinvantveer
github_username:  reinvantveer

# Build settings
markdown: kramdown
