# Site settings
title: "Rein van 't Veer"
email: reinvantveer at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Rein van 't Veer, geospatial and semantic web developer.
  All content copyright Rein van 't Veer CC-BY-SA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reinvantveer.github.io" # the base hostname & protocol for your site
twitter_username: reinvantveer
github_username:  reinvantveer
repository: reinvantveer/reinvantveer.github.io

# Build settings
theme: jekyll-theme-dinky
markdown: kramdown
ignore:
  - node_modules
exclude:
  - node_modules
  - plugin/markdown/example.md
  - css/theme/README.md
