---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  group: cache.example.com
  names:
    kind: Memcached
    plural: memcacheds
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
