on: workflow_dispatch

jobs:
  test-operator-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Install k3s
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Create namespaces
        run: |
          for ns in argo-events argo memcached
          do 
              kubectl create ns ${ns}
          done

      - name: Install Argo Events cluster-wide (don't do this in production)
        run: |
          kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
          # Install with a validating admission controller
          kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml

      - name: Install EventBus
        run: kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml

      - name: Install Argo Workflows
        run: kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.7/install.yaml

      - name: Install the Memcached custom resource definition
        run: kubectl apply -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/crd.yaml

      - name: Install the rule-based access control (RBAC) config
        run: kubectl apply -n argo-events -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/rbac.yaml

      - name: Validate that the rules allow watching Memcached resources
        run: kubectl -n argo-events auth can-i list memcached.cache.example.com/memcacheds --as=system:serviceaccount:operators:memcached-sa

      - name: Validate that the rules allow creating Deployments
        run: kubectl -n argo-events auth can-i create deployments --as=system:serviceaccount:operators:memcached-sa

      - name: Validate that the rules allow creating Workflows
        run: kubectl -n argo-events auth can-i create workflows.argoproj.io/workflows --as=system:serviceaccount:operators:memcached-sa

      - name: Install the EventSource in the argo-events namespace
        run: kubectl apply -n argo-events -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/event-source.yaml

      - name: Install the Sensor in the argo-events namespace
        run: kubectl apply -n argo-events -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/sensor.yaml

      - name: Deploy our Memcached resource
        run: kubectl apply -n argo-events -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/memcached.yaml
