on: workflow_dispatch

jobs:
  test-operator-installation:
    runs-on: ubuntu-latest
    env:
      EVENTS_NS: argo-events

    steps:
      - name: Install k3s
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Create namespaces
        run: |
          for ns in argo-events argo memcached
          do 
              kubectl create ns ${ns}
          done

      - name: Install Argo Events cluster-wide (don't do this in production)
        run: |
          kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
          # Install with a validating admission controller
          kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml

      - name: Install EventBus
        run: kubectl apply -n ${EVENTS_NS} -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml

      - name: Install Argo Workflows
        run: kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.7/install.yaml

      - name: Install the Memcached custom resource definition
        run: kubectl apply -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/crd.yaml

      - name: Install the rule-based access control (RBAC) config
        run: kubectl apply -n ${EVENTS_NS} -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/rbac.yaml

      - name: Validate that the rules allow watching Memcached resources, create Deployments, Pods, Workflows
        run: |
          kubectl -n ${EVENTS_NS} auth can-i list   memcached.cache.example.com/memcacheds --as=system:serviceaccount:${EVENTS_NS}:memcached-sa
          kubectl -n ${EVENTS_NS} auth can-i create deployments --as=system:serviceaccount:${EVENTS_NS}:memcached-sa
          kubectl -n ${EVENTS_NS} auth can-i create pods --as=system:serviceaccount:${EVENTS_NS}:memcached-sa
          kubectl -n ${EVENTS_NS} auth can-i create workflow.argoproj.io/workflows --as=system:serviceaccount:${EVENTS_NS}:memcached-sa
          sleep 10

      - name: Install the EventSource in the events namespace
        run: kubectl apply -n ${EVENTS_NS} -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/event-source.yaml

      - name: Install the Sensor in the events namespace
        run: |
          kubectl apply -n ${EVENTS_NS} -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/sensor.yaml

      - name: Validate availability of the Sensor
        run: |
          kubectl wait -n ${EVENTS_NS} --for=condition=Deployed --timeout=60s sensor/memcached-sensor
          kubectl wait -n ${EVENTS_NS} --for=condition=DependenciesProvided --timeout=60s sensor/memcached-sensor
          kubectl wait -n ${EVENTS_NS} --for=condition=TriggersProvided --timeout=60s sensor/memcached-sensor

      - name: Deploy our Memcached resource
        run: kubectl apply -n ${EVENTS_NS} -f https://raw.githubusercontent.com/reinvantveer/reinvantveer.github.io/master/_includes/memcached/memcached.yaml

      - name: Validate that a Workflow was created
        run: |
          sleep 10
          kubectl get -n ${EVENTS_NS} workflows

      - name: Validate that the deployment was created
        run: kubectl wait -n ${EVENTS_NS} --for=condition=available --timeout=60s deployment/memcached-deployment
